### ISSUE TITLE
Sample does not work with Visual Studio 2015

### ISSUE THREAD

**Issue by jozefizso** [Azure-Samples/AzureAD-WebApp-OpenIdConnect-AspNet5#17]
I tried the sample but it fails to run in Visual Studio 2015 Update 3.

I cloned the code, ran solution file and hit F5. This should start IIS Express and server the `https://localhost:44353/` website. Visual Studio will display the error message instead.

```
---------------------------
Microsoft Visual Studio
---------------------------
An error occurred attempting to determine the process id of dotnet.exe which is hosting your application. One or more errors occurred.
---------------------------
OK   
---------------------------
```

How is the sample supposed to be run locally?

**Comment by tdjastrzebski** [comment]
I have the same problem. So far found no working solution. In general there is a lot trouble with ASP.Net Core. A lot contradictory information, not working examples. It seems like the problem is caused by IIS Express not starting. Perhaps SSL certificate problem

**Comment by AlexanderPilhar** [comment]
I did encounter the same problem - here is how I made it work:
Open launchSettings.json and make "applicationUrl" start with "http://" instead of "https://". Next you need to change one of the ports (in the sample they are both the same), otherwise IIS Express won't start since it can't make both - http and https - listen to the same port. Now you should be able to run the sample. The sample will launch using http. You can simply change it to use https just by editing the url (don't forget to use the correct port; there might be a warning about the certificate). Also, update the settings in azure to whatever ports you are using now.
I hope this does the trick for you.

**Comment by Mandur** [comment]
Thanks @AlexanderPilhar your solution worked

**Comment by KaiWalter** [comment]
I ran into the same problem.

I fixed it by repairing the IIS Express installation and running this script from http://codegists.com/snippet/powershell/trust-iis-express-development-certificateps1_elanhasson_powershell


    ipmo PKI
    $name = [GUID]::NewGuid()
    $cerFile = "$env:TEMP\$name.cer"
    $certs = Get-ChildItem Cert:\LocalMachine\My -DnsName localhost -SSLServerAuthentication | ?     {($_.FriendlyName -eq 'IIS Express Development Certificate') -and ($_.SignatureAlgorithm.FriendlyName -ieq 'sha256RSA') -and ($_.EnhancedKeyUsageList.Count -eq 1)}
    if ($certs.Count -eq 0)
    {
        Write-Error 'Cannot find any SHA256 certificate generated by IIS Express. Please make sure that the latest version of IIS Express is installed.'
    }
    else
    {
        foreach ($cert in $certs)
        {
            Export-Certificate -Cert $cert.PSPath -FilePath $cerFile -Type CERT | Out-Null
            Import-Certificate -FilePath $cerFile -CertStoreLocation Cert:\CurrentUser\Root | Out-Null
            Remove-Item $cerFile -Force
        }
        Write-Host 'Successfully installed the certificate to Trusted Root Certification Authorities of the current user.'
    }

**Comment by monomial** [comment]
If you run the project _without_ debugging then it will prompt you to accept the IIS Express SSL certificate.  After that you can run it with debugging on.
